{% set name = "firewxpy" %}
{% set version = "1.2.112" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/firewxpy-{{ version }}.tar.gz
  sha256: 7f804ddf8177e2b2d6701c958aa40a6716baef34cb1883194f2d0a7577897b7b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=64
    - pip
  run:
    - python >=3.10
    - matplotlib-base >=3.7
    - protobuf >=3.20.3
    - metpy >=1.5.1
    - netcdf4 >=1.7.1
    - numpy >=1.24
    - pandas >=2.2
    - siphon >=0.10.0
    - xarray >=2023.1.0
    - pysolar >=0.11
    - pygrib >=2.1.4
    - cfgrib >=0.9.10.4
    - cartopy >=0.21.0
    - imageio >=2.34.0

test:
  imports:
    - firewxpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/edrewitz/firewxpy
  summary: Weather Analysis and Forecasting For Fire Weather
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/edrewitz/firewxpy/blob/main/Documentation/Landing_Page.md

extra:
  recipe-maintainers:
    - edrewitz
