{% set name = "firewxpy" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/firewxpy-{{ version }}.tar.gz
  sha256: 5dde953d8b7cb60150868a287e88afeea68fcfcd8cf6fcc36f9b1e01d9ab5321

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=68.0
    - pip
  run:
    - python >=3.8
    - matplotlib-base >=3.7
    - protobuf ==3.20.3
    - metpy >=1.5.1
    - netcdf4 >=1.7.1
    - numpy >=1.24
    - pandas >=2
    - siphon >=0.9
    - xarray ==2024.02.0
    - pysolar >=0.11
    - pygrib >=2.1.4
    - cfgrib >=0.9.10.4
    - cartopy >=0.21.0
    - imageio >=2.34.0

test:
  imports:
    - firewxpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/edrewitz/firewxpy
  summary: Weather Analysis and Forecasting For Fire Weather
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/edrewitz/firewxpy/tree/main/Documentation

extra:
  recipe-maintainers:
    - edrewitz
