{% set python_min = '3.10' %}
{% set name = "firewxpy" %}
{% set version = "1.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/firewxpy-{{ version }}.tar.gz
  sha256: ce9b316489c2ec74e2c3685ea3d797bec63800fe101e6fa67e1fb0e7dee52d19

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.7
    - protobuf >=3.20.3
    - metpy >=1.5.1
    - netcdf4 >=1.7.1
    - numpy >=1.24
    - pandas >=2.2
    - siphon >=0.10.0
    - xarray >=2023.1.0
    - pysolar >=0.11
    - cfgrib >=0.9.10.4
    - cartopy >=0.21.0
    - pytz >=2024.1

test:
  imports:
    - firewxpy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/edrewitz/firewxpy
  summary: Weather Analysis and Forecasting For Fire Weather
  license: MIT
  license_file: LICENSE
  doc_url: https://pypi.org/project/firewxpy/

extra:
  recipe-maintainers:
    - edrewitz
